packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  unrs-resolver: true
  utf-8-validate: true

onlyBuiltDependencies:
  - '@reown/appkit'
  - bufferutil
  - esbuild
  - keccak
  - msgpackr-extract
  - unrs-resolver
  - utf-8-validate
