export const campaignEscrowAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'initialOwner', type: 'address', internalType: 'address' },
      { name: 'agentAddress', type: 'address', internalType: 'address' },
      { name: 'registryAddress', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'createCampaign',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'totalBudget', type: 'uint128', internalType: 'uint128' },
      { name: 'cpmRate', type: 'uint64', internalType: 'uint64' },
      { name: 'maxPayoutPerClip', type: 'uint128', internalType: 'uint128' },
      { name: 'minViews', type: 'uint32', internalType: 'uint32' },
      { name: 'deadline', type: 'uint64', internalType: 'uint64' },
      { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'rulesHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: 'campaignId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'registerClip',
    inputs: [
      { name: 'campaignId', type: 'uint256', internalType: 'uint256' },
      { name: 'clipper', type: 'address', internalType: 'address' },
      { name: 'videoIdHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: 'clipId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseMilestone',
    inputs: [
      {
        name: 'att',
        type: 'tuple',
        internalType: 'struct ICampaignEscrow.Attestation',
        components: [
          { name: 'clipId', type: 'uint256', internalType: 'uint256' },
          { name: 'campaignId', type: 'uint256', internalType: 'uint256' },
          { name: 'clipper', type: 'address', internalType: 'address' },
          { name: 'videoIdHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'verifiedViews', type: 'uint32', internalType: 'uint32' },
          { name: 'sourceMatchBps', type: 'uint16', internalType: 'uint16' },
          { name: 'safetyBps', type: 'uint16', internalType: 'uint16' },
          { name: 'anomalyBps', type: 'uint16', internalType: 'uint16' },
          { name: 'evidenceHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'nonce', type: 'uint256', internalType: 'uint256' },
          { name: 'expiry', type: 'uint64', internalType: 'uint64' },
        ],
      },
      { name: 'signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimHoldback',
    inputs: [{ name: 'clipId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'flagClip',
    inputs: [
      { name: 'clipId', type: 'uint256', internalType: 'uint256' },
      { name: 'reasonHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'flagAnomaly',
    inputs: [
      { name: 'clipId', type: 'uint256', internalType: 'uint256' },
      { name: 'evidenceHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'topUpCampaign',
    inputs: [
      { name: 'campaignId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdrawRemaining',
    inputs: [{ name: 'campaignId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getCampaign',
    inputs: [{ name: 'campaignId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ICampaignEscrow.Campaign',
        components: [
          { name: 'brand', type: 'address', internalType: 'address' },
          { name: 'cpmRate', type: 'uint64', internalType: 'uint64' },
          { name: 'status', type: 'uint8', internalType: 'enum ICampaignEscrow.CampaignStatus' },
          { name: 'token', type: 'address', internalType: 'address' },
          { name: 'deadline', type: 'uint64', internalType: 'uint64' },
          { name: 'minViews', type: 'uint32', internalType: 'uint32' },
          { name: 'totalBudget', type: 'uint128', internalType: 'uint128' },
          { name: 'remaining', type: 'uint128', internalType: 'uint128' },
          { name: 'allocated', type: 'uint128', internalType: 'uint128' },
          { name: 'maxPayoutPerClip', type: 'uint128', internalType: 'uint128' },
          { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'rulesHash', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClip',
    inputs: [{ name: 'clipId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ICampaignEscrow.Clip',
        components: [
          { name: 'campaignId', type: 'uint256', internalType: 'uint256' },
          { name: 'clipper', type: 'address', internalType: 'address' },
          { name: 'paidViews', type: 'uint32', internalType: 'uint32' },
          { name: 'lastReleaseAt', type: 'uint32', internalType: 'uint32' },
          { name: 'status', type: 'uint8', internalType: 'enum ICampaignEscrow.ClipStatus' },
          { name: 'releasedAmount', type: 'uint128', internalType: 'uint128' },
          { name: 'holdbackAmount', type: 'uint128', internalType: 'uint128' },
          { name: 'holdbackUnlockAt', type: 'uint64', internalType: 'uint64' },
          { name: 'videoIdHash', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdrawnByBrand',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'usedNonce',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'CampaignCreated',
    inputs: [
      { name: 'campaignId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'brand', type: 'address', indexed: true, internalType: 'address' },
      { name: 'budget', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'cpmRate', type: 'uint64', indexed: false, internalType: 'uint64' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ClipRegistered',
    inputs: [
      { name: 'clipId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'campaignId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'clipper', type: 'address', indexed: true, internalType: 'address' },
      { name: 'videoIdHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MilestoneReleased',
    inputs: [
      { name: 'clipId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'fromViews', type: 'uint32', indexed: false, internalType: 'uint32' },
      { name: 'toViews', type: 'uint32', indexed: false, internalType: 'uint32' },
      { name: 'released', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'holdback', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'evidenceHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'HoldbackClaimed',
    inputs: [
      { name: 'clipId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint128', indexed: false, internalType: 'uint128' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ClipFlagged',
    inputs: [
      { name: 'clipId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'by', type: 'address', indexed: true, internalType: 'address' },
      { name: 'reasonHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
] as const;
